/**
 * Converts snarkjs verification_key.json into Rust constants
 * compatible with groth16-solana's Groth16Verifyingkey format.
 *
 * groth16-solana expects all curve points in big-endian affine coordinates.
 * G1 points: 64 bytes (32 bytes x, 32 bytes y)
 * G2 points: 128 bytes (64 bytes x [c1,c0], 64 bytes y [c1,c0])
 *
 * Usage: npx tsx circuits/scripts/extract-vk-rust.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const BUILD_DIR = join(__dirname, '..', 'build');
const VK_PATH = join(BUILD_DIR, 'verification_key.json');
const OUTPUT_PATH = join(BUILD_DIR, 'verifying_key.rs');

interface VerificationKey {
  protocol: string;
  curve: string;
  nPublic: number;
  vk_alpha_1: string[];
  vk_beta_2: string[][];
  vk_gamma_2: string[][];
  vk_delta_2: string[][];
  IC: string[][];
}

function bigintToBytes32BE(n: string): number[] {
  const bi = BigInt(n);
  const bytes: number[] = [];
  for (let i = 31; i >= 0; i--) {
    bytes.push(Number((bi >> BigInt(i * 8)) & 0xFFn));
  }
  return bytes;
}

function formatG1Point(point: string[]): string {
  const x = bigintToBytes32BE(point[0]);
  const y = bigintToBytes32BE(point[1]);
  const all = [...x, ...y];
  return formatByteArray(all);
}

function formatG2Point(point: string[][]): string {
  // G2 point: [[x_c0, x_c1], [y_c0, y_c1]]
  // groth16-solana expects: x_c1, x_c0, y_c1, y_c0 (each 32 bytes, big-endian)
  const x_c1 = bigintToBytes32BE(point[0][1]);
  const x_c0 = bigintToBytes32BE(point[0][0]);
  const y_c1 = bigintToBytes32BE(point[1][1]);
  const y_c0 = bigintToBytes32BE(point[1][0]);
  const all = [...x_c1, ...x_c0, ...y_c1, ...y_c0];
  return formatByteArray(all);
}

function formatByteArray(bytes: number[]): string {
  const lines: string[] = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const chunk = bytes.slice(i, i + 16);
    lines.push('    ' + chunk.map(b => `${b},`).join(' '));
  }
  return lines.join('\n');
}

// Read verification key
const vk: VerificationKey = JSON.parse(readFileSync(VK_PATH, 'utf-8'));

console.log(`Protocol: ${vk.protocol}`);
console.log(`Curve: ${vk.curve}`);
console.log(`Public inputs: ${vk.nPublic}`);
console.log(`IC length: ${vk.IC.length}`);

// Generate Rust file
let rust = `// Auto-generated by extract-vk-rust.ts
// DO NOT EDIT — regenerate with: npx tsx circuits/scripts/extract-vk-rust.ts
//
// For use with groth16-solana crate
// Public inputs: ${vk.nPublic} (root, nullifierHash, recipient, denomination)

use groth16_solana::groth16::Groth16Verifyingkey;

/// Groth16 verifying key for the withdraw circuit
pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${vk.nPublic},

    vk_alpha_g1: [
${formatG1Point(vk.vk_alpha_1)}
    ],

    vk_beta_g2: [
${formatG2Point(vk.vk_beta_2)}
    ],

    vk_gamme_g2: [
${formatG2Point(vk.vk_gamma_2)}
    ],

    vk_delta_g2: [
${formatG2Point(vk.vk_delta_2)}
    ],

    vk_ic: &[
`;

for (let i = 0; i < vk.IC.length; i++) {
  rust += `        [\n${formatG1Point(vk.IC[i])}\n        ],\n`;
}

rust += `    ],
};
`;

writeFileSync(OUTPUT_PATH, rust);
console.log(`\nRust verifying key written to: ${OUTPUT_PATH}`);