// SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;

/**
 * @title HasherFactory
 * @dev Factory contract to deploy MiMCSponge hasher from raw bytecode.
 * The MiMCSponge bytecode is generated by circomlibjs/src/mimcsponge_gencontract.js
 * with seed="mimcsponge" and nRounds=220, matching the circom MiMCSponge(2, 220, 1) template.
 *
 * Usage:
 *   1. Deploy HasherFactory
 *   2. Call deployHasher(bytecode) where bytecode is the output of:
 *      import { createCode } from 'circomlibjs/src/mimcsponge_gencontract.js';
 *      createCode('mimcsponge', 220)
 *   3. The returned address implements IHasher.MiMCSponge(uint256, uint256, uint256)
 *
 * The bytecode is passed as a parameter (not embedded) because it's ~11.7KB
 * which would push this contract near the 24KB deployment limit.
 */
contract HasherFactory {
    event HasherDeployed(address hasher);

    /**
     * @dev Deploy MiMCSponge hasher contract from raw bytecode.
     * @param _bytecode The full creation bytecode from mimcsponge_gencontract.js
     * @return hasher The deployed hasher contract address
     */
    function deployHasher(bytes memory _bytecode) external returns (address hasher) {
        assembly {
            hasher := create(0, add(_bytecode, 0x20), mload(_bytecode))
        }
        
        require(hasher != address(0), "HasherFactory: deployment failed");
        emit HasherDeployed(hasher);
    }
}
